variable "db_event_subscription_enabled" {
  description = "A boolean flag to enable/disable the subscription. Defaults to true"
  type        = bool
  default     = true
}
variable "db_event_subscription_event_categories" {
  description = "A list of event categories for a SourceType that you want to subscribe to"
  type        = list(string)
  default     = []
}
variable "db_event_subscription_name" {
  description = "The name of the DB event subscription. By default generated by Terraform"
  type        = string
  default     = ""
}
variable "db_event_subscription_sns_topic" {
  description = "The SNS topic to send events to"
  type        = string
}
variable "db_event_subscription_source_ids" {
  description = " A list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. If specified, a source_type must also be specified"
  type        = list(string)
  default     = []
}
variable "db_event_subscription_source_type" {
  description = "The type of source that will be generating the events. Valid options are db-instance, db-security-group, db-parameter-group, db-snapshot, db-cluster or db-cluster-snapshot. If not set, all sources will be subscribed to"
  type        = string
  default     = ""
}
