variable "efs_file_system_availability_zone_name" {
  description = "The AWS Availability Zone in which to create the file system. Used to create a file system that uses One Zone storage classes"
  type        = string
  default     = null
}
variable "efs_file_system_creation_token" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform"
  type        = string
  default     = null
}
variable "efs_file_system_encrypted" {
  description = "If true, the disk will be encrypted"
  type        = bool
  default     = false
}
variable "efs_file_system_kms_key_id" {
  description = "The ARN for the KMS encryption key. When specifying kms_key_id, encrypted needs to be set to true"
  type        = string
  default     = null
}
variable "efs_file_system_performance_mode" {
  description = "The file system performance mode. Can be either \"generalPurpose\" or \"maxIO\" (Default: \"generalPurpose\")"
  type        = string
  default     = null
}
variable "efs_file_system_provisioned_throughput_in_mibps" {
  description = "The throughput, measured in MiB/s, that you want to provision for the file system. Only applicable with throughput_mode set to provisioned"
  type        = number
  default     = null
}
variable "efs_file_system_tags" {
  description = "A map of tags to assign to the file system. If configured with a provider default_tags configuration block present, tags with matching keys will overwrite those defined at the provider-level"
  type        = map(string)
  default     = {}
}
variable "efs_file_system_throughput_mode" {
  description = "Throughput mode for the file system. Defaults to bursting. Valid values: bursting, provisioned, or elastic. When using provisioned, also set provisioned_throughput_in_mibps "
  type        = string
  default     = null
}
variable "efs_file_system_lifecycle_policy" {
  description = "A file system lifecycle policy object"
  type        = list(object({
    transition_to_ia                    = optional(string)
    transition_to_primary_storage_class = optional(string)
  }))
  default     = []
}
