variable "lambda_permission_action" {
  description = "The AWS Lambda action you want to allow in this statement. (e.g., lambda:InvokeFunction)"
  type        = string
}
variable "lambda_permission_event_source_token" {
  description = "The Event Source Token to validate. Used with Alexa Skills"
  type        = string
  default     = null
}
variable "lambda_permission_function_name" {
  description = "Name of the Lambda function whose resource policy you are updating"
  type        = string
}
variable "lambda_permission_function_url_auth_type" {
  description = "Lambda Function URLs authentication type. Valid values are: AWS_IAM or NONE. Only supported for lambda:InvokeFunctionUrl action"
  type        = string
  default     = null
}
variable "lambda_permission_principal" {
  description = "The principal who is getting this permission e.g., s3.amazonaws.com, an AWS account ID, or AWS IAM principal, or AWS service principal such as events.amazonaws.com or sns.amazonaws.com"
  type        = string
  default     = null
}
variable "lambda_permission_qualifier" {
  description = "Query parameter to specify function version or alias name. The permission will then apply to the specific qualified ARN e.g., arn:aws:lambda:aws-region:acct-id:function:function-name:2"
  type        = string
  default     = null
}
variable "lambda_permission_source_account" {
  description = "This parameter is used when allowing cross-account access, or for S3 and SES. The AWS account ID (without a hyphen) of the source owner"
  type        = string
  default     = null
}
variable "lambda_permission_source_arn" {
  description = "When the principal is an AWS service, the ARN of the specific resource within that service to grant permission to. Without this, any resource from principal will be granted permission – even if that resource is from another account. For S3, this should be the ARN of the S3 Bucket. For EventBridge events, this should be the ARN of the EventBridge Rule. For API Gateway, this should be the ARN of the API"
  type        = string
  default     = null
}
variable "lambda_permission_statement_id" {
  description = "A unique statement identifier. By default generated by Terraform"
  type        = string
  default     = null
}
variable "lambda_permission_statement_id_prefix" {
  description = "A statement identifier prefix. Terraform will generate a unique suffix. Conflicts with statement_id"
  type        = string
  default     = null
}
variable "lambda_permission_principal_org_id" {
  description = "The identifier for your organization in AWS Organizations. Use this to grant permissions to all the AWS accounts under this organization"
  type        = string
  default     = null
}
