variable "api_gateway_api_key_customer_id" {
  description = "An Amazon Web Services Marketplace customer identifier, when integrating with the Amazon Web Services SaaS Marketplace"
  type        = string
}
variable "api_gateway_api_key_description" {
  description = "API key description. Defaults to \"Managed by Terraform\""
  type        = string
  default     = ""
}
variable "api_gateway_api_key_enabled" {
  description = "Whether the API key can be used by callers. Defaults to true"
  type        = bool
  default     = null
}
variable "api_gateway_api_key_name" {
  description = "Name of the API key"
  type        = string
}
variable "api_gateway_api_key_tags" {
  description = "Key-value map of resource tags. If configured with a provider default_tags configuration block present, tags with matching keys will overwrite those defined at the provider-level"
  type        = map(string)
  default     = {}
}
variable "api_gateway_api_key_value" {
  description = "Value of the API key. If specified, the value must be an alphanumeric string between 20 and 128 characters. If not specified, it will be automatically generated by AWS on creation"
  type        = string
  default     = null
}
